import { Platform } from 'react-native';

export const userClassNames = {
  page: 'relative flex-1 overflow-hidden',
  content: 'w-full max-w-[1600px] self-center gap-7',
  headerSection: 'justify-between gap-5',
  headerCopy: 'max-w-[760px] flex-1 gap-2.5',
  title: 'font-headline text-[42px] tracking-[-1px]',
  description: 'max-w-[680px] font-body text-lg font-light leading-7',
  ctaWrap: 'rounded-lg',
  cta: 'min-h-[54px] flex-row items-center gap-2.5 rounded-lg px-6',
  ctaText: 'font-label text-[10px] uppercase tracking-[2.2px]',
  overviewSection: 'justify-between gap-4',
  viewSwitch: 'flex-row items-center gap-2 rounded-lg p-1',
  viewSwitchButton: 'min-h-[42px] items-center justify-center rounded-md px-[18px]',
  viewSwitchButtonText: 'font-label text-[11px] uppercase tracking-[1.7px]',
  overviewStats: 'flex-row flex-wrap gap-6',
  overviewStat: 'min-w-[132px] gap-1.5',
  overviewLabel: 'font-label text-[10px] uppercase tracking-[2.4px]',
  overviewValue: 'font-headline text-[28px] tracking-[-0.6px]',
  filterShell: 'gap-3 rounded-[10px] border p-[14px]',
  filterRow: 'flex-row flex-wrap items-center gap-3',
  filterField: 'min-h-12 flex-row items-center justify-between gap-2.5 rounded-[7px] border px-[14px]',
  filterFieldText: 'flex-1 font-body text-[13px] font-semibold',
  clearButton: 'min-h-11 flex-row items-center justify-center gap-2 rounded-[7px] px-[14px]',
  clearButtonText: 'font-label text-[10px] uppercase tracking-[2px]',
  tableShell: 'overflow-hidden rounded-[10px] border',
  headerRow: 'min-h-[58px] flex-row items-center border-b px-6',
  headerText: 'font-label text-[10px] uppercase tracking-[2.4px]',
  cell: 'min-w-0 justify-center py-[18px]',
  userInfo: 'min-w-0 flex-row items-center gap-3.5',
  avatarFrame: 'h-[52px] w-[52px] shrink-0 overflow-hidden rounded-lg border',
  userCopy: 'min-w-0 flex-1 gap-1',
  userName: 'font-body text-sm font-bold',
  userEmail: 'font-body text-xs leading-[18px]',
  roleBadge: 'self-start rounded-full border px-2.5 py-1.5',
  roleText: 'font-label text-[10px] uppercase tracking-[1.6px]',
  salonName: 'font-body text-[13px] font-semibold',
  salonLocation: 'mt-0.5 font-body text-[11px] leading-[18px]',
  statusRow: 'flex-row items-center gap-2',
  statusDot: 'h-2 w-2 rounded-full',
  statusText: 'font-label text-[10px] uppercase tracking-[1.8px]',
  occupancyWrap: 'gap-2',
  occupancyHeader: 'flex-row items-center justify-between gap-2',
  occupancyLabel: 'font-label text-[9px] uppercase tracking-[1.5px]',
  occupancyValue: 'font-body text-xs font-bold',
  occupancyBar: 'h-1 w-24 overflow-hidden rounded-full',
  occupancyBarFill: 'h-full rounded-full',
  occupancyNa: 'font-label text-[10px] uppercase tracking-[1.8px]',
  actionsRow: 'flex-row items-center gap-1',
  iconAction: 'h-[34px] w-[34px] items-center justify-center rounded-full',
  emptyState: 'mx-5 my-5 min-h-[240px] items-center justify-center gap-3 rounded-[10px] border px-6',
  emptyTitle: 'font-body text-base font-bold',
  emptyDescription: 'max-w-[420px] text-center font-body text-sm leading-5',
  mobileList: 'gap-[14px] p-4',
  mobileCard: 'gap-4 rounded-[10px] border p-4',
  mobileCardTop: 'flex-row items-start justify-between gap-3',
  mobileMetaGrid: 'flex-row flex-wrap gap-[14px]',
  mobileMetaItem: 'min-w-[146px] flex-1 gap-1',
  mobileMetaLabel: 'font-label text-[10px] uppercase tracking-[2px]',
  mobileMetaValue: 'font-body text-[13px] font-semibold',
  mobileMetaSubValue: 'font-body text-[11px] leading-4',
  mobileActions: 'flex-row justify-end gap-1.5',
  paginationBar: 'min-h-[52px] flex-row flex-wrap items-center justify-between gap-3 border-t px-5 py-2.5',
  paginationText: 'font-label text-[10px] uppercase tracking-[1.8px]',
  paginationControls: 'flex-row items-center gap-1',
  paginationButton: 'h-7 w-7 items-center justify-center rounded-md',
  pageButton: 'h-7 min-w-[28px] items-center justify-center rounded-md',
  pageButtonText: 'font-body text-[11px] font-bold',
  pageEllipsis: 'w-5 items-center justify-center',
  pageEllipsisText: 'font-body text-[11px] tracking-wide',
  groupedGrid: 'flex-row flex-wrap gap-4 p-4',
  groupedCard: 'min-h-[220px] gap-4 rounded-[10px] border p-[18px]',
  groupedCardHeader: 'gap-1.5',
  groupedCardTitle: 'font-headline text-[22px] tracking-[-0.4px]',
  groupedCardLocation: 'font-body text-xs leading-[18px]',
  groupedStatsRow: 'flex-row flex-wrap gap-[14px]',
  groupedStat: 'min-w-[98px] gap-1',
  groupedStatLabel: 'font-label text-[10px] uppercase tracking-[1.8px]',
  groupedStatValue: 'font-body text-xl font-bold',
  groupedOccupancy: 'gap-2',
  groupedOccupancyText: 'font-body text-xs font-semibold',
  insightsGrid: 'gap-5',
  growthCard: 'min-h-[250px] justify-between overflow-hidden rounded-[10px] border p-7',
  growthCopy: 'z-[1] max-w-[560px] gap-3',
  growthTitle: 'font-headline text-[28px] tracking-[-0.5px]',
  growthDescription: 'font-body text-sm leading-6',
  growthMetrics: 'flex-row flex-wrap gap-[18px]',
  insightMetricCard: 'min-w-[132px] gap-1.5 rounded-lg border px-4 py-3',
  insightMetricLabel: 'font-label text-[10px] uppercase tracking-[2px]',
  insightMetricValue: 'font-headline text-[28px] tracking-[-0.4px]',
  growthIcon: 'absolute -right-2 -top-1.5',
  exportCard: 'min-h-[250px] justify-between gap-[18px] rounded-[10px] border p-6',
  exportTitle: 'font-headline text-2xl tracking-[-0.4px]',
  exportDescription: 'max-w-[340px] font-body text-[13px] leading-[22px]',
  exportActions: 'gap-3',
  exportButton: 'min-h-[50px] flex-row items-center justify-between gap-3 rounded-lg border px-4',
  exportButtonText: 'font-label text-[10px] uppercase tracking-[2.1px]',
  groupedContainer: 'gap-6',
  groupedSection: 'overflow-hidden rounded-lg border',
  sectionHeader: 'gap-4 border-b px-6 py-[22px]',
  sectionHeaderRow: 'flex-row flex-wrap items-center justify-between gap-4',
  sectionIdentity: 'min-w-[260px] flex-1 flex-row items-center gap-4',
  sectionIconFrame: 'h-[52px] w-[52px] shrink-0 items-center justify-center rounded-md border',
  sectionTitleWrap: 'min-w-0 flex-1 gap-2',
  sectionTitleRow: 'flex-row flex-wrap items-center gap-2.5',
  sectionTitle: 'shrink font-headline text-2xl tracking-[-0.5px]',
  planPill: 'min-h-6 items-center justify-center rounded-full border px-2.5 py-1',
  planPillText: 'font-label text-[10px] uppercase tracking-[1.8px]',
  sectionMetaRow: 'flex-row flex-wrap items-center gap-2',
  sectionMetaText: 'font-label text-[10px] uppercase tracking-[2.2px]',
  sectionActions: 'flex-row flex-wrap items-center gap-2.5',
  sectionBody: 'p-6',
  membersGrid: 'flex-row flex-wrap gap-4',
  memberCard: 'min-h-[236px] gap-4 overflow-hidden rounded-md border p-5',
  memberCardTop: 'flex-row items-start justify-between gap-3',
  memberAvatarWrap: 'relative h-16 w-16',
  memberAvatarFrame: 'h-16 w-16 overflow-hidden rounded-md border',
  memberStatusDot: 'absolute -bottom-0.5 -right-0.5 h-[14px] w-[14px] rounded-full border-2',
  memberMenuButton: 'h-[34px] w-[34px] items-center justify-center rounded-full',
  memberCopy: 'gap-2',
  memberName: 'font-headline text-[22px] tracking-[-0.4px]',
  memberTitle: 'font-label text-[10px] uppercase tracking-[2.4px]',
  memberSpecialtiesWrap: 'flex-row flex-wrap gap-2 border-t pt-4',
  memberSpecialtyPill: 'rounded-sm px-2.5 py-[7px]',
  memberSpecialtyText: 'font-label text-[10px] uppercase tracking-[1.4px]',
  addCard: 'min-h-[236px] items-center justify-center gap-[14px] rounded-md border-2 border-dashed p-5',
  addCardIconWrap: 'h-12 w-12 items-center justify-center rounded-full',
  addCardText: 'font-label text-[10px] uppercase tracking-[2.2px]',
} as const;

export function getUserPanelShadow(theme: 'light' | 'dark') {
  return Platform.OS === 'web'
    ? ({
        boxShadow:
          theme === 'dark'
            ? '0 26px 60px rgba(0, 0, 0, 0.34)'
            : '0 24px 54px rgba(27, 27, 32, 0.08)',
      } as const)
    : {
        shadowColor: '#000000',
        shadowOpacity: theme === 'dark' ? 0.22 : 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 12 },
        elevation: 8,
      };
}
