import { Platform, StyleSheet } from 'react-native';

import { Typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  gridOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: Platform.OS === 'web' ? 1 : 0,
    backgroundSize: '40px 40px',
    pointerEvents: 'none',
  } as any,
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    width: '100%',
    maxWidth: 1600,
    alignSelf: 'center',
    gap: 28,
  },
  headerSection: {
    justifyContent: 'space-between',
    gap: 20,
  },
  headerCopy: {
    flex: 1,
    maxWidth: 760,
    gap: 10,
  },
  title: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 42,
    letterSpacing: -1,
  },
  description: {
    ...Typography.bodyLg,
    fontWeight: '300',
    maxWidth: 680,
  },
  ctaWrap: {
    borderRadius: 8,
  },
  cta: {
    minHeight: 54,
    borderRadius: 8,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ctaText: {
    ...Typography.labelMd,
    fontFamily: 'Manrope-Bold',
    letterSpacing: 2.2,
  },
  overviewSection: {
    justifyContent: 'space-between',
    gap: 16,
  },
  viewSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 4,
    borderRadius: 8,
  },
  viewSwitchButton: {
    minHeight: 42,
    paddingHorizontal: 18,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewSwitchButtonText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 11,
    letterSpacing: 1.7,
  },
  overviewStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
  },
  overviewStat: {
    minWidth: 132,
    gap: 6,
  },
  overviewLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.4,
  },
  overviewValue: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.6,
  },
  filterShell: {
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    gap: 12,
  },
  stickyFilters: {
    position: 'sticky',
    top: 18,
    zIndex: 30,
  } as any,
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'center',
  },
  filterField: {
    minHeight: 48,
    borderRadius: 7,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  filterFieldText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
  },
  clearButton: {
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  clearButtonText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
  },
  tableShell: {
    borderRadius: 10,
    borderWidth: 1,
    overflow: 'hidden',
  },
  headerRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    paddingHorizontal: 24,
  },
  headerText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.4,
  },
  row: {
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  cell: {
    justifyContent: 'center',
    minWidth: 0,
    paddingVertical: 18,
  },
  cellUser: {
    flex: 2.55,
  },
  cellRole: {
    flex: 1.05,
    paddingRight: 16,
  },
  cellSalon: {
    flex: 1.65,
    paddingRight: 18,
  },
  cellStatus: {
    flex: 1,
    paddingRight: 16,
  },
  cellCapacity: {
    flex: 1.25,
    paddingRight: 16,
  },
  cellActions: {
    flex: 1.05,
    alignItems: 'flex-end',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minWidth: 0,
  },
  avatarFrame: {
    width: 52,
    height: 52,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    flexShrink: 0,
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  userCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  userName: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
  },
  userEmail: {
    ...Typography.bodyMd,
    fontSize: 12,
    lineHeight: 18,
  },
  roleBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  roleText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.6,
  },
  salonName: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
  },
  salonLocation: {
    ...Typography.bodyMd,
    fontSize: 11,
    lineHeight: 18,
    marginTop: 2,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  statusText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.8,
  },
  occupancyWrap: {
    gap: 8,
  },
  occupancyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  occupancyLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 1.5,
  },
  occupancyValue: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
  },
  occupancyBar: {
    width: 96,
    height: 4,
    borderRadius: 999,
    overflow: 'hidden',
  },
  occupancyBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  occupancyNa: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.8,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  iconAction: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    minHeight: 240,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
    borderRadius: 10,
    margin: 20,
    borderWidth: 1,
  },
  emptyTitle: {
    ...Typography.titleMd,
    fontFamily: 'Manrope-Bold',
  },
  emptyDescription: {
    ...Typography.bodyMd,
    textAlign: 'center',
    maxWidth: 420,
  },
  mobileList: {
    padding: 16,
    gap: 14,
  },
  mobileCard: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    gap: 16,
  },
  mobileCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  mobileMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  mobileMetaItem: {
    minWidth: 146,
    flex: 1,
    gap: 4,
  },
  mobileMetaLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
  },
  mobileMetaValue: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
  },
  mobileMetaSubValue: {
    ...Typography.bodyMd,
    fontSize: 11,
    lineHeight: 16,
  },
  mobileActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 6,
  },
  paginationBar: {
    minHeight: 68,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  paginationText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.8,
  },
  paginationControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  paginationButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageButton: {
    minWidth: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  pageButtonText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
  },
  groupedGrid: {
    padding: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  groupedCard: {
    minHeight: 220,
    borderWidth: 1,
    borderRadius: 10,
    padding: 18,
    gap: 16,
  },
  groupedCardHeader: {
    gap: 6,
  },
  groupedCardTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 22,
    letterSpacing: -0.4,
  },
  groupedCardLocation: {
    ...Typography.bodyMd,
    fontSize: 12,
    lineHeight: 18,
  },
  groupedStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  groupedStat: {
    minWidth: 98,
    gap: 4,
  },
  groupedStatLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.8,
  },
  groupedStatValue: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 20,
  },
  groupedOccupancy: {
    gap: 8,
  },
  groupedOccupancyText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
  },
  insightsGrid: {
    gap: 20,
  },
  growthCard: {
    minHeight: 250,
    borderRadius: 10,
    borderWidth: 1,
    padding: 28,
    overflow: 'hidden',
    justifyContent: 'space-between',
  },
  growthCopy: {
    gap: 12,
    maxWidth: 560,
    zIndex: 1,
  },
  growthTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.5,
  },
  growthDescription: {
    ...Typography.bodyMd,
    fontSize: 14,
    lineHeight: 24,
  },
  growthMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
  },
  insightMetricCard: {
    minWidth: 132,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 6,
  },
  insightMetricLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
  },
  insightMetricValue: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.4,
  },
  growthIcon: {
    position: 'absolute',
    right: -8,
    top: -6,
  },
  exportCard: {
    minHeight: 250,
    borderWidth: 1,
    borderRadius: 10,
    padding: 24,
    gap: 18,
    justifyContent: 'space-between',
  },
  exportTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 24,
    letterSpacing: -0.4,
  },
  exportDescription: {
    ...Typography.bodyMd,
    fontSize: 13,
    lineHeight: 22,
    maxWidth: 340,
  },
  exportActions: {
    gap: 12,
  },
  exportButton: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  exportButtonText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.1,
  },
  webInteractiveCard: {
    transition: 'transform 180ms ease, background-color 180ms ease, border-color 180ms ease, box-shadow 220ms ease',
  } as any,
  webInteractiveButton: {
    transition: 'background-color 160ms ease, border-color 160ms ease, opacity 160ms ease, transform 160ms ease',
    cursor: 'pointer',
  } as any,
  webRowTransition: {
    transition: 'background-color 180ms ease',
  } as any,
});
