import { Platform, StyleSheet } from 'react-native';

import { Typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  gridOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: Platform.OS === 'web' ? 1 : 0,
    backgroundSize: '40px 40px',
    pointerEvents: 'none',
  } as any,
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    width: '100%',
    maxWidth: 1640,
    alignSelf: 'center',
    gap: 28,
  },
  heroSection: {
    gap: 20,
  },
  heroMain: {
    justifyContent: 'space-between',
    gap: 20,
  },
  heroCopy: {
    flex: 1,
    gap: 14,
    maxWidth: 860,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusBadgeText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.2,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 13,
  },
  heroTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 54,
    lineHeight: 62,
    letterSpacing: -1.8,
  },
  heroLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  heroLocationText: {
    ...Typography.labelMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 11,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  heroActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  contentGrid: {
    gap: 24,
    alignItems: 'stretch',
  },
  leftColumn: {
    gap: 24,
    minWidth: 0,
  },
  rightColumn: {
    gap: 24,
    minWidth: 0,
  },
  glassCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 24,
    overflow: 'hidden',
  },
  identityAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
  },
  cardEyebrow: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 3.2,
    textTransform: 'uppercase',
    marginBottom: 20,
  },
  infoStack: {
    gap: 20,
  },
  infoBlock: {
    gap: 5,
  },
  infoLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  ownerText: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 24,
    letterSpacing: -0.4,
  },
  infoValueLg: {
    ...Typography.bodyLg,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 16,
  },
  infoValueSm: {
    ...Typography.bodyMd,
    fontSize: 13,
    lineHeight: 20,
  },
  infoValueLink: {
    ...Typography.bodyMd,
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  subscriptionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  planText: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 24,
    letterSpacing: -0.5,
  },
  subscriptionStatusPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  subscriptionStatusText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 1.8,
  },
  subscriptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  subscriptionMeta: {
    minWidth: 130,
    gap: 4,
    flex: 1,
  },
  subscriptionActions: {
    gap: 10,
    marginTop: 8,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  metricItem: {
    minWidth: 180,
  },
  metricCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 18,
    gap: 12,
  },
  metricLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  metricValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metricValue: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.6,
  },
  sparklineRow: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
  },
  sparklineBar: {
    flex: 1,
    borderRadius: 999,
    minHeight: 8,
  },
  tableShell: {
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  tableHeader: {
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  tableHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flexWrap: 'wrap',
  },
  tableActionText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  staffHeaderRow: {
    minHeight: 52,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
  },
  tableColumnLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  staffRow: {
    minHeight: 86,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
  },
  staffCell: {
    minWidth: 0,
    justifyContent: 'center',
    paddingVertical: 16,
  },
  staffCellPerson: {
    flex: 2.4,
  },
  staffCellRole: {
    flex: 1.4,
  },
  staffCellPerformance: {
    flex: 1.5,
  },
  staffCellActions: {
    flex: 0.7,
    alignItems: 'flex-end',
  },
  staffPersonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minWidth: 0,
  },
  staffAvatarFrame: {
    width: 42,
    height: 42,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 1,
    flexShrink: 0,
  },
  staffAvatar: {
    width: '100%',
    height: '100%',
  },
  staffName: {
    ...Typography.bodyMd,
    fontFamily: 'NotoSerif-Bold',
    fontSize: 15,
  },
  staffRole: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 10,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  performanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  performanceTrack: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
  },
  performanceBar: {
    height: '100%',
    borderRadius: 999,
  },
  performanceText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  staffMobileList: {
    padding: 16,
    gap: 12,
  },
  staffMobileCard: {
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  staffMobileTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 1,
  },
  serviceItem: {
    minWidth: 260,
  },
  serviceCard: {
    padding: 20,
    borderWidth: 1,
    gap: 14,
    minHeight: 150,
    justifyContent: 'space-between',
  },
  serviceTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 20,
    letterSpacing: -0.4,
  },
  serviceMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  serviceMetaText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  servicePrice: {
    ...Typography.bodyLg,
    fontFamily: 'Manrope-Bold',
    fontSize: 24,
  },
  popularityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  popularityBars: {
    flexDirection: 'row',
    gap: 2,
  },
  popularityBar: {
    width: 4,
    height: 16,
    borderRadius: 999,
  },
  footer: {
    paddingTop: 8,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  footerText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 48,
    gap: 16,
  },
  emptyTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  emptyDescription: {
    ...Typography.bodyMd,
    textAlign: 'center',
    maxWidth: 420,
  },
});
