import { Platform, StyleSheet } from 'react-native';

import { Typography } from '@/constants/typography';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  gridOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: Platform.OS === 'web' ? 1 : 0,
    backgroundSize: '40px 40px',
    pointerEvents: 'none',
  } as any,
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    width: '100%',
    maxWidth: 1600,
    alignSelf: 'center',
    gap: 32,
  },
  headerSection: {
    justifyContent: 'space-between',
    gap: 20,
  },
  headerCopy: {
    flex: 1,
    maxWidth: 720,
    gap: 10,
  },
  eyebrow: {
    ...Typography.labelMd,
    fontFamily: 'Manrope-Bold',
    letterSpacing: 4,
  },
  title: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 38,
    letterSpacing: -0.8,
  },
  description: {
    ...Typography.bodyLg,
    fontWeight: '300',
    maxWidth: 620,
  },
  ctaWrap: {
    borderRadius: 8,
  },
  cta: {
    minHeight: 54,
    borderRadius: 8,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ctaText: {
    ...Typography.labelMd,
    fontFamily: 'Manrope-Bold',
    letterSpacing: 2.2,
  },
  filtersGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  filterItem: {
    minWidth: 190,
  },
  filterCard: {
    minHeight: 82,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 7,
    borderWidth: 1,
    justifyContent: 'space-between',
  },
  filterLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 9,
    letterSpacing: 1.8,
  },
  filterValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  filterValue: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  totalCard: {
    minHeight: 82,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 7,
    borderWidth: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  totalValue: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.6,
    marginTop: 6,
  },
  tableShell: {
    borderRadius: 10,
    borderWidth: 1,
    overflow: 'hidden',
  },
  headerRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    paddingHorizontal: 24,
  },
  headerText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.4,
  },
  row: {
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  cell: {
    justifyContent: 'center',
    minWidth: 0,
    paddingVertical: 18,
  },
  cellSalon: {
    flex: 2.4,
  },
  cellOwner: {
    flex: 1.6,
    paddingRight: 20,
  },
  cellLocation: {
    flex: 1.45,
    paddingRight: 16,
  },
  cellStatus: {
    flex: 1.05,
    paddingRight: 16,
  },
  cellPlan: {
    flex: 0.95,
    paddingRight: 16,
  },
  cellActions: {
    flex: 1.1,
    alignItems: 'flex-end',
  },
  salonInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minWidth: 0,
  },
  salonThumbFrame: {
    width: 52,
    height: 52,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    flexShrink: 0,
  },
  salonThumb: {
    width: '100%',
    height: '100%',
  },
  salonCopy: {
    minWidth: 0,
    flex: 1,
    gap: 4,
  },
  salonName: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 14,
  },
  salonId: {
    ...Typography.bodyMd,
    fontSize: 12,
    lineHeight: 18,
  },
  ownerName: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 14,
  },
  ownerEmail: {
    ...Typography.bodyMd,
    fontSize: 11,
    lineHeight: 18,
    marginTop: 2,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  locationText: {
    ...Typography.bodyMd,
    fontSize: 12,
    lineHeight: 18,
    flexShrink: 1,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.6,
  },
  planRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  planDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  planText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  iconAction: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: {
    minHeight: 260,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
    borderWidth: 1,
    borderRadius: 10,
    margin: 20,
  },
  emptyTitle: {
    ...Typography.titleMd,
    fontFamily: 'Manrope-Bold',
  },
  emptyDescription: {
    ...Typography.bodyMd,
    textAlign: 'center',
    maxWidth: 420,
  },
  mobileList: {
    padding: 16,
    gap: 14,
  },
  mobileCard: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    gap: 16,
  },
  mobileCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  mobileMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  mobileMetaItem: {
    minWidth: 150,
    flex: 1,
    gap: 4,
  },
  mobileMetaLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
  },
  mobileMetaValue: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-SemiBold',
    fontSize: 13,
  },
  mobileMetaSubValue: {
    ...Typography.bodyMd,
    fontSize: 11,
    lineHeight: 16,
  },
  mobileActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 6,
  },
  paginationBar: {
    minHeight: 68,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  paginationText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 1.8,
  },
  paginationControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  paginationButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageButton: {
    minWidth: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  pageButtonText: {
    ...Typography.bodyMd,
    fontFamily: 'Manrope-Bold',
    fontSize: 12,
  },
  insightsGrid: {
    gap: 20,
  },
  growthCard: {
    flex: 1.9,
    minHeight: 280,
    borderRadius: 10,
    borderWidth: 1,
    padding: 28,
    overflow: 'hidden',
    justifyContent: 'space-between',
  },
  growthCopy: {
    gap: 14,
    maxWidth: 520,
    zIndex: 1,
  },
  growthTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 28,
    letterSpacing: -0.5,
  },
  growthDescription: {
    ...Typography.bodyMd,
    fontSize: 14,
    lineHeight: 24,
  },
  growthMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 32,
    marginTop: 8,
  },
  growthLabel: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2,
    marginBottom: 6,
  },
  growthValue: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 32,
    letterSpacing: -0.6,
  },
  growthIcon: {
    position: 'absolute',
    right: -12,
    bottom: -18,
  },
  systemCard: {
    flex: 1,
    minHeight: 280,
    borderRadius: 10,
    borderWidth: 1,
    padding: 24,
    justifyContent: 'space-between',
    gap: 18,
  },
  systemTitle: {
    fontFamily: 'NotoSerif-Bold',
    fontSize: 24,
    letterSpacing: -0.4,
    marginBottom: 12,
  },
  systemStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  systemPulse: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  systemStatusText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.2,
  },
  systemDescription: {
    ...Typography.bodyMd,
    lineHeight: 22,
    maxWidth: 320,
  },
  systemButton: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  systemButtonText: {
    ...Typography.labelSm,
    fontFamily: 'Manrope-Bold',
    fontSize: 10,
    letterSpacing: 2.1,
    textAlign: 'center',
  },
  webInteractiveCard: {
    transition: 'transform 180ms ease, background-color 180ms ease, border-color 180ms ease',
  } as any,
  webInteractiveButton: {
    transition: 'background-color 160ms ease, border-color 160ms ease, opacity 160ms ease, transform 160ms ease',
    cursor: 'pointer',
  } as any,
  webRowTransition: {
    transition: 'background-color 180ms ease',
  } as any,
});
